name: CI/CD workflow for clculator

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout to clculator
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run coverage

      - name: Deploy
        run: echo "App successfully deployed."


  

    
